name: Atualização Diária de Status

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "YancaBot"
          git config user.email "yancafer@users.noreply.github.com"

      - name: Atualizar arquivo README
        run: |
          echo "Atualizado em $(date -u)" > update.txt
          git add update.txt
          git commit -m "Atualização automática: $(date -u)" || echo "Nada para commitar"
          git push
